// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUz949yzW9LlRFes4JLcE6rsRIg3cE_Xc',
    appId: '1:447003124819:web:ecd89e51562545e56612a6',
    messagingSenderId: '447003124819',
    projectId: 'madproject-9de37',
    authDomain: 'madproject-9de37.firebaseapp.com',
    storageBucket: 'madproject-9de37.firebasestorage.app',
    measurementId: 'G-DMW20WV8GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndGS6oF0ZysVcXkUJpl9CJkZzOu8feq0',
    appId: '1:447003124819:android:fda11a1c7f96e0e56612a6',
    messagingSenderId: '447003124819',
    projectId: 'madproject-9de37',
    storageBucket: 'madproject-9de37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwJMJtLUq8vprnvGTxPoY5l_YpKDVAy4',
    appId: '1:447003124819:ios:26d5f512a0fc77ac6612a6',
    messagingSenderId: '447003124819',
    projectId: 'madproject-9de37',
    storageBucket: 'madproject-9de37.firebasestorage.app',
    androidClientId: '447003124819-5henttl6vd59qh3hpfoeeo99k17bu0kc.apps.googleusercontent.com',
    iosClientId: '447003124819-qlvc5boa8n9co9lr0h2d05or7rge0fqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );

}